In [1]:
import numpy
n = numpy.arange(27)

In [2]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [3]:
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [29]:
m = numpy.asarray([[123,12,123,12,33],[],[]])

In [30]:
type(m)

numpy.ndarray

In [31]:
import cv2

In [47]:
im_g = cv2.imread("smallgray.png",0)

In [48]:
print(im_g)

[[143 147 182]
 [121 255  97]
 [104 255 255]
 [158 125 134]
 [187 198 209]]


In [49]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [51]:
im_g[0:2, 0:2]

array([[143, 147],
       [121, 255]], dtype=uint8)

In [52]:
im_g.shape

(5, 3)

In [54]:
for i in im_g.T:
    print(i)

[143 121 104 158 187]
[147 255 255 125 198]
[182  97 255 134 209]


In [55]:
for i in im_g.flat:
    print(i)

143
147
182
121
255
97
104
255
255
158
125
134
187
198
209


In [60]:
ims = numpy.hstack((im_g, im_g, im_g))

In [61]:
print(ims)

[[143 147 182 143 147 182 143 147 182]
 [121 255  97 121 255  97 121 255  97]
 [104 255 255 104 255 255 104 255 255]
 [158 125 134 158 125 134 158 125 134]
 [187 198 209 187 198 209 187 198 209]]


In [62]:
ims = numpy.vstack((im_g, im_g, im_g))

In [64]:
print(ims)

[[143 147 182]
 [121 255  97]
 [104 255 255]
 [158 125 134]
 [187 198 209]
 [143 147 182]
 [121 255  97]
 [104 255 255]
 [158 125 134]
 [187 198 209]
 [143 147 182]
 [121 255  97]
 [104 255 255]
 [158 125 134]
 [187 198 209]]


In [68]:
lst = numpy.hsplit(ims, 3)

In [71]:
print(lst)

[array([[143],
       [121],
       [104],
       [158],
       [187],
       [143],
       [121],
       [104],
       [158],
       [187],
       [143],
       [121],
       [104],
       [158],
       [187]], dtype=uint8), array([[147],
       [255],
       [255],
       [125],
       [198],
       [147],
       [255],
       [255],
       [125],
       [198],
       [147],
       [255],
       [255],
       [125],
       [198]], dtype=uint8), array([[182],
       [ 97],
       [255],
       [134],
       [209],
       [182],
       [ 97],
       [255],
       [134],
       [209],
       [182],
       [ 97],
       [255],
       [134],
       [209]], dtype=uint8)]
